"""Add Stripe payment fields

Revision ID: 0e5042995e0f
Revises: c7f57f083480
Create Date: 2025-11-23 11:39:59.669766

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e5042995e0f"
down_revision = "c7f57f083480"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("stripe_customer_id", sa.String(length=120), nullable=True)
        )
        batch_op.add_column(
            sa.Column("stripe_payment_intent_id", sa.String(length=120), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "stripe_checkout_session_id", sa.String(length=120), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("stripe_subscription_id", sa.String(length=120), nullable=True)
        )
        batch_op.add_column(
            sa.Column("payment_status", sa.String(length=30), nullable=True)
        )
        batch_op.add_column(
            sa.Column("webhook_received_at", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(sa.Column("extra_metadata", sa.JSON(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_payments_stripe_checkout_session_id"),
            ["stripe_checkout_session_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_payments_stripe_customer_id"),
            ["stripe_customer_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_payments_stripe_payment_intent_id"),
            ["stripe_payment_intent_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_payments_stripe_subscription_id"),
            ["stripe_subscription_id"],
            unique=False,
        )
        batch_op.create_foreign_key("fk_payments_user_id", "user", ["user_id"], ["id"])

    with op.batch_alter_table("petition_templates", schema=None) as batch_op:
        batch_op.alter_column(
            "is_global",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("1"),
        )

    with op.batch_alter_table("petition_types", schema=None) as batch_op:
        batch_op.alter_column(
            "is_implemented",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("stripe_customer_id", sa.String(length=120), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_user_stripe_customer_id"),
            ["stripe_customer_id"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_stripe_customer_id"))
        batch_op.drop_column("stripe_customer_id")

    with op.batch_alter_table("petition_types", schema=None) as batch_op:
        batch_op.alter_column(
            "is_implemented",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )

    with op.batch_alter_table("petition_templates", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("1"),
        )
        batch_op.alter_column(
            "is_global",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_constraint("fk_payments_user_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_payments_stripe_subscription_id"))
        batch_op.drop_index(batch_op.f("ix_payments_stripe_payment_intent_id"))
        batch_op.drop_index(batch_op.f("ix_payments_stripe_customer_id"))
        batch_op.drop_index(batch_op.f("ix_payments_stripe_checkout_session_id"))
        batch_op.drop_column("extra_metadata")
        batch_op.drop_column("webhook_received_at")
        batch_op.drop_column("payment_status")
        batch_op.drop_column("stripe_subscription_id")
        batch_op.drop_column("stripe_checkout_session_id")
        batch_op.drop_column("stripe_payment_intent_id")
        batch_op.drop_column("stripe_customer_id")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
