"""Add LGPD compliance models

Revision ID: 9204bd05a89e
Revises: 914ae0c76849
Create Date: 2025-12-24 20:21:57.261140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9204bd05a89e'
down_revision = '914ae0c76849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymization_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('request_reason', sa.Text(), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=True),
    sa.Column('anonymization_method', sa.String(length=50), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('anonymized_data', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['processed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('consent_purpose', sa.Text(), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=True),
    sa.Column('consent_version', sa.String(length=20), nullable=True),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('consent_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('request_reason', sa.Text(), nullable=False),
    sa.Column('deletion_scope', sa.Text(), nullable=True),
    sa.Column('retention_reason', sa.Text(), nullable=True),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('appeal_deadline', sa.DateTime(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('deletion_summary', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['processed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('data_category', sa.String(length=100), nullable=False),
    sa.Column('data_fields', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('legal_basis', sa.String(length=100), nullable=True),
    sa.Column('consent_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consent_id'], ['data_consents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_processing_logs')
    op.drop_table('deletion_requests')
    op.drop_table('data_consents')
    op.drop_table('anonymization_requests')
    # ### end Alembic commands ###
