"""Add default_values to PetitionTemplate

Revision ID: c2ba792fc123
Revises: 0e5042995e0f
Create Date: 2025-11-29 22:36:05.796004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ba792fc123'
down_revision = '0e5042995e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_values', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition_templates', schema=None) as batch_op:
        batch_op.drop_column('default_values')

    # ### end Alembic commands ###
