"""Initial migration

Revision ID: d394c145c36b
Revises: 
Create Date: 2025-11-21 06:36:33.131419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd394c145c36b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('force_password_change', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('force_password_change')
        batch_op.drop_column('password_history')
        batch_op.drop_column('password_expires_at')
        batch_op.drop_column('password_changed_at')

    # ### end Alembic commands ###
